.github/PULL_REQUEST_TEMPLATE.md
🔒 Close #1
- Pull Request Convention
- [MC2 GreedySquirrel Pull Request Convention](https://github.com/DeveloperAcademy-POSTECH/MC2-Team2-GreedySquirrel/blob/dev/.github/PULL_REQUEST_TEMPLATE.md)
=> [Documentation] #1 : Pull Request Convention

.gitignore
=> [Project] #3 : Gitignore

.gitattributes
🔒 Close #5 
- Gitattributes 추가
- [git-scm](https://git-scm.com/book/ko/v2/Git맞춤-Git-Attributes)
=> [Project] #5 : Gitattributes

README.md
🔒 Close #8 
- README.md를 확인할 수 있다.
- 개인 github profile과 잘 연결되어 있는지 확인해 주세요.
- [MC2-Team2-GreedySquirrel](https://github.com/DeveloperAcademy-POSTECH/MC2-Team2-GreedySquirrel)
=> [Documentation] #8 : Update README.md

DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj, DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.xcworkspace/contents.xcworkspacedata, DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/AppDelegate.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/AccentColor.colorset/Contents.json, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/AppIcon.appiconset/Contents.json, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/Contents.json, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/LaunchScreen.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Info.plist, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/SceneDelegate.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/Shop.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #10 
- Xcode Project를 포함시킨다.
- screenshot
- ![image](https://user-images.githubusercontent.com/81242125/176344674-dcf59353-ab5e-460f-8c9d-363e94b03238.jpeg)
- 폴더링 확인 부탁드립니다.
=> [Project] # 10 : Create Xcode Project

DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Info.plist, DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/Shop.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Manager/LocationManager.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Resource/DaeguGoodPriceShop.json, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController+.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #22 
🔒 Close #25 
- 유저의 현재 위치를 받아온다
- 지도에 착한 가게 업소 위치에 annotation을 보여준다
- [SampleMapApp](https://github.com/sustainable-git/SampleMapApp)
- [CustomAnnotation](https://kokojong.tistory.com/m/7)
=> [Feature] User Location, Annotation

DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/Shop.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
🔒 Close #31 
- Shop Entity 내용 변경
- ShopCategory와 ShopSubCategory라는 이름이 적절한지 확인 부탁드립니다.
=> [Refactor] #31 : Refactor shop entity

DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
🔒 Close #36 
- Implement MapView UI
- I don't know why shadow is not accepted
=> [Refactor] #36 : Implement MapView UI

DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #43
- 즐겨찾기에 추가할 수 있는 로직 추가(추후 상세화면에서 추가 가능)
- 즐겨찾기 버튼 눌렀을 때 즐겨찾기 업소 필터링(현재 아무것도 추가되어 있지 않기 때문에 나오지 않는다)
- ShopSubcategory에서 ShopCategory를 찾아올 수 있는 로직 추가
- shop의 id 배열을 userdefaults로 저장해서 사용하는게 맞는지
- filterling 방법(더 좋은 방법이 있을 것 같다)
=> [Feature] #43 : Add favorite shop logic

DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj, DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/DataItem.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DefaultModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/Shared/HeaderView.swift
🔒 Close #60 
- 카테고리 상세 리스트 생성
- 카테고리 데이터 생성
- 카테고리 셀 생성
- 카테고리 섹션에 대한 레이아웃 구현
- Diffable datasource를 이용해 컬렉션뷰 구현
- Compositional Layouts를 이용해 섹션 구분
=> [Feature] #60: DetailCategoryList 구현

DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/DataItem.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DefaultModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
🔒 Close #61
- 즐겨찾기 가게 리스트 추가
- 즐겨찾기 데이터 생성
- 즐겨찾기 셀 구현
- 즐겨찾기 레이아웃 구현
- Diffable datasource를 이용해 컬렉션뷰 구현
- Compositional Layouts를 이용해 섹션 구분
=> [Feature] #61 : 즐겨찾기 가게 리스트 구현

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DefaultModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
🔒 Close #62 
- 일반 가게 목록 추가
- 일반 가게 데이터 구조체 생성
- 일반 가게 셀 구현
- 일반 가게 레이아웃 구현
- Diffable datasource를 이용해 컬렉션뷰 구현
- Compositional Layouts를 이용해 섹션 구분
=> [Feature] #62 : 일반 가게 리스트 구현

DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #58 
- 어노테이션의 info 버튼을 누르면 detail modal이 나오고, detail modal에 선택한 어노테이션에 대한 정보를 전달한다.
- detali modal 안에 즐겨찾기 버튼을 추가해서 선택한 업소를 즐겨찾기 할 수 있다.
=> [Feature] #58 : Create annotation press action and favorite button.

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
🔒Close #75
🔒Close #73
- 유저가 선택한 업체에 대한 디테일 뷰 제공
- 유저가 선택한 업체 주소를 복사하는 버튼 및 기능 제공
- 유저가 선택한 업체에 전화를 할 수 있는 버튼 및 기능 제공
- 데이터 받아오기
- UI 컴포넌트 위치
- [Rectangle Radius](https://stackoverflow.com/questions/33927914/how-can-i-set-the-cornerradius-of-a-uistackview)
- [UIStack View](https://stackoverflow.com/questions/30728062/add-views-in-uistackview-programmatically)
=> [Feature] #75, #73 : DetailModalView 구현

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
🔒 Close #74
- 유저가 CellView 내의 CallButton을 눌렀을 때, 해당 Cell 업체 번호로 전화하기 제공
- shopCallNumber 변수를 통해서 storeCallNumber 데이터 받아오기
=> [Feature] #74 : CellView CallButton 전화 기능 구현

DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ModalHeight.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
🔒 Close #82
- 줌 위치가 더 이쁘게 변경되었습니다.
=> [Refactor] #82 : Refactor zoom

DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/UIFont+Extension.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
🔒 Close #85
- 작은 화면, 큰 글자에도 깨지지 않아요!
- <img height=500 src="https://user-images.githubusercontent.com/81242125/178640266-a88c520f-a9f3-43b7-9b83-d8286add8fd0.jpeg">
=> [Refactor] #85 : Category View UI

DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #90
🔒 Close #91
- 카테고리 뷰에 즐겨찾기 기능이 정상 동작합니다.
=> [Feature] #90, #91 : CategoryView favorite logic

DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #93
- favorite 적용이 되도록 하였습니다.
=> [Bug] #93 : Fix favorite bug

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
🔒 Close #87
- Detail modal이 올라올 때 default modal이 올라오는 방식에서 default modal 제거
- Category modal과 겹치는 문제 수정
=> [Refactor] #87 : Refactor Detail Modal

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
=> [Feature] #96 : Unfiltering

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
🔒 Close #102
- 카테고리에서 즐겨찾기된 업소를 누르면 지도가 이동하고 줌이 된다.
=> [Feature] #102 : Zoom logic of category favorite view

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
🔒 Close #107
- ModalView에 x 버튼을 없앴습니다.
=> [Refactor] #107 : Delete back button

DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ModalHeight.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
=> [Refactor] #97 : Change Modal Height

DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ModalHeight.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
🔒 Close #104 
- 고정 색을 system color로 변경
=> [Refactor] #104 : Apply Dark mode

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
🔒 Close #114
- UITextView로 그려지던 DetailModalView의 컴포넌트들을 UILabel로 변경
- 변수들 이름 통일화
- 클로저의 이름과 내부 변수의 이름이 같을 때, 다르게 변경
- Shop의 정보를 업데이트 해주는 코드들을 updateDetailModalView()메소드에 통합
- 레이아웃이 잘 잡혀있는지 리뷰해주세요
=> [Refactor] #114 : replace UITextView with UILabel

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
🔒 Close #118
- 지도의 다른부분을 선택하면 Annotation image가 내려간 이미지로 변경됩니다.
=> [Bug] #118 : Annotation deselection

DaeguGoodPriceShop/DaeguGoodPriceShop/Application/AppDelegate.swift
=> [Bug] #122 : Portrait fix

DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #127 
- 즐겨찾기 버튼 클릭시 tint color 변경 적용
- 카테고리 버튼 클릭시 tint color 변경 적용
- 카테고리 버튼 클릭시 모달이 올라갔다 내려갔다 적용
- 이름이 비슷한 메서드들이 많아서 나중에 리팩토링한다면 네이밍을 다시해야할 것 같아요.
=> [Bug] #127 : Fix bugs that do not apply changes when clicking a button

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
🔒 Close #128 
- 상세 정보 모달에서 즐겨찾기 버튼 개선
=> [Bug] #128 : Implement favourite button UI in detail modal

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift
🔒 Close #133 
- drag gesture의 범위를 모달 전체로 바꿨습니다.
=> [Bug] #133 : Change drag gesture area

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
=> [Bug] HOTFIX : Change modal view layout

DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #140
- 어노테이션 갱신 방법을 전체 삭제 후 추가하는 방식에서 삭제해야 할 어노테이션만 삭제하고 추가해야 할 어노테이션만 추가하는 방식으로 변경
- 정상 동작 여부 확인해 주세요
- 성능적으로 손해가 있을지 궁금합니다
=> [Bug] #140 : Change Annotation Update Method

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #143
-  Map과 Modal의 정보 동기화
- Annotation을 누르면 Detail Modal을 띄운다.
- Detail Modal을 내리면 Annotation도 선택 해제된다.
- Category와 Favorite이 동시에 선택이 가능하므로 Favorite 여부를 바꾸더라도 Category  Modal을 내리지 않는다.
- 기능들이 정상적으로 작동하는지
- 어색한 기능은 없는지
=> [Bug] #143 : Syncronize map and modal

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
=> [Bug] HOTFIX : Resolve conflict

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
🔒 Close #148 
- subTitleAddressView에 Layout 적용
- AutoLayout이 제대로 적용 되어 있는지.
=> [Bug] #148 : Adjust Detail Modal View subTitleAddressView layout

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
🔒 Close #150 
- store 모달에 즐겨찾기 섹션에 모든 업소가 추가되어 있는 문제 해결
- 코드 리팩토링 필요
=> [Bug] #150 : Fix store favorite list

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
=> [Bug] HOTFIX : Fix unfiltering unavailable

DaeguGoodPriceShop/DaeguGoodPriceShop/Resource/DaeguGoodPriceShop.json, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
🔒 Close #156
업소 DetailView의 Title(업소이름)옆의 Search_icon 누르면 Go to GoodShop Web URL
- screenshot(optional)
=> [Feature] #156 : Go to GoodShop Web URL

DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
🔒 Close #158 
- Right, Left Padding값 각각 15로 통일
- Title Label Font Size 및 레이아웃 조정
- 
- 레이아웃을 확인해주세요
=> [Bug]Adjust UI Components

DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Co-authored-by: imparang <jeongjaeyn@gmail.com>
🔒 Close #159
- 동기적으로 불러오는 getShops를 비동기적으로 불러오도록 변경
- self.shops를 비동기적으로 변경해야 하기 때문에 model을 struct에서 class로 변경
=> [Refactor] #159 : Data async fetching

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapLocationViewModel.swift
🔒 Close #162
- View와 ViewModel 사이의 data binding을 closure로 변경
=> [Refactor] #162 : Data binding from combine to closure

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
🔒 Close #169
- 상세 카테고리 버튼이 눌렸을 때 모양 변경
=> [Refactor] #169 : Change Subcategory button

DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
🔒 Close #172 
- 버튼이 안눌렸을 때 아이콘 색 변경
=> [Refactor] #172 : Change button icon color

DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
Co-authored-by: imparang <jeongjaeyn@gmail.com>
🔒 Close #171 
- 비동기 logic 단순화
=> [Refactor] #171 : Refactor JSON async logic

DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj, DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/Model/StoreListItem.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/DetailModalViewModel.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
🔒 Close #177 
🔒 Close #178 
- Refactor 과정에서 StoreListModalView 가로 scroll Bug가 아름답게 해결되었습니다.
- Data Binding을 이용하여 mapView가 자동 update 됩니다
- @YebinKim 너무 많은 양의 코드에 대한 리뷰를 요청드려서 죄송합니다...
- property와 function의 naming 확인해주시면 감사드리겠습니다.
- 얘는 왜 경고를 주나요..?
=> [Refactor] #177, #178 : Data binding, Business logic

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
🔒 Close #184
- Binding을 통해 isShowingCategory가 변경되면 색상이 자동으로 변경됩니다.
- Data binding으로 Delegate pattern을 아애 없애버릴까 하여 고민이 됩니다...
- 다음 sprint가 존재한다면... 하는걸로
=> [Bug] #184 : Sync CategoryButton and StoreListModalView

DaeguGoodPriceShop/DaeguGoodPriceShop/Model/LocationManager.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift, DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
Co-authored-by: Yeongwoo-Poding <yw1221@g.skku.edu>
🔒 Close #167
- Shop Distance Calculation in DetailModalViewController
- Shop Distance Calculation in StoreListViewCell
- Shop Menu & Price in StoreListViewCell,, Instead ShopAddress
-  DetailModalViewController 내의 func initModal() 에서 shopDistance처리 부분
-  StoreListViewCell 내의 func configure 에서 shopDistance처리 부분
=> [Refactor] #167 : Shop Distance Calculation 

README.md
🔒 Close #190 
- README.md 개선
- 스크린샷 괜찮나요?
=> [Documentation] #190 : Update README.md

DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
🔒 Close #192
- 더 이상 선택된 annotation이 다시 clustering이 일어나지 않습니다.
- [clustering을 멈추자](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-DaeguGoodPriceShop/wiki/Clustering을-멈추자)
=> [Bug] #192 : Fix selected annotation clustering

README.md
🔒 Close #194
- UT를 진행해 보았는데, 사람들이 Wiki를 따로 읽지 않았습니다.
- README.md 내용만 보더라도 Wiki를 작성했다는 것을 알 수 있게 README.md에 내용을 기입해 두었습니다.
=> [Documentation] #194 : Update README.md
